# Generated by Django 4.2.5 on 2024-12-07 08:47

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_cocina', models.CharField(blank=True, max_length=100, null=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('delivery_dentro', models.BooleanField(default=False)),
                ('imagen_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen_url')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('id_dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.dueñorestaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('vehiculo', models.CharField(choices=[('A pie', 'A pie'), ('Carro', 'Carro'), ('Moto', 'Moto'), ('Bicicleta', 'Bicicleta')], max_length=20)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartidores', to='restaurantes.restaurante')),
            ],
        ),
    ]
