# Generated by Django 4.2.5 on 2024-12-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DueñoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('token_acceso', models.CharField(blank=True, max_length=255, null=True)),
                ('token_refresh', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('token_acceso', models.CharField(blank=True, max_length=255, null=True)),
                ('token_refresh', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
